version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/"
    schedule:
      interval: "daily"
      time: "22:05"
    commit-message:
      prefix: "chore(deps):"
    allow:
      - dependency-type: "all"
    rebase-strategy: "auto"